import type { Club } from "../types";

export const CLUBS: Club[] = [
  {
    id: "real-madrid",
    name: "Real Madrid",
    league: "LaLiga",
    strength: 96,
    colors: ["#f8fafc", "#c4b5fd"],
    continental: true,
    wageFactor: 1.3,
  },
  {
    id: "barcelona",
    name: "FC Barcelona",
    league: "LaLiga",
    strength: 94,
    colors: ["#a50044", "#004d98"],
    continental: true,
    wageFactor: 1.24,
  },
  {
    id: "atletico",
    name: "Atlético de Madrid",
    league: "LaLiga",
    strength: 89,
    colors: ["#cb3524", "#152a55"],
    continental: true,
    wageFactor: 1.12,
  },
  {
    id: "arsenal",
    name: "Arsenal",
    league: "Premier League",
    strength: 93,
    colors: ["#ef0107", "#f8fafc"],
    continental: true,
    wageFactor: 1.22,
  },
  {
    id: "liverpool",
    name: "Liverpool",
    league: "Premier League",
    strength: 94,
    colors: ["#c8102e", "#00b2a9"],
    continental: true,
    wageFactor: 1.24,
  },
  {
    id: "man-city",
    name: "Manchester City",
    league: "Premier League",
    strength: 94,
    colors: ["#6cabdd", "#1c2c5b"],
    continental: true,
    wageFactor: 1.28,
  },
  {
    id: "chelsea",
    name: "Chelsea",
    league: "Premier League",
    strength: 88,
    colors: ["#034694", "#f8fafc"],
    continental: true,
    wageFactor: 1.12,
  },
  {
    id: "man-united",
    name: "Manchester United",
    league: "Premier League",
    strength: 84,
    colors: ["#da291c", "#fbe122"],
    continental: false,
    wageFactor: 1.15,
  },
  {
    id: "tottenham",
    name: "Tottenham Hotspur",
    league: "Premier League",
    strength: 84,
    colors: ["#132257", "#f8fafc"],
    continental: true,
    wageFactor: 1.08,
  },
  {
    id: "psg",
    name: "Paris Saint-Germain",
    league: "Ligue 1",
    strength: 95,
    colors: ["#004170", "#da291c"],
    continental: true,
    wageFactor: 1.27,
  },
  {
    id: "bayern",
    name: "FC Bayern München",
    league: "Bundesliga",
    strength: 94,
    colors: ["#dc052d", "#0066b2"],
    continental: true,
    wageFactor: 1.23,
  },
  {
    id: "dortmund",
    name: "Borussia Dortmund",
    league: "Bundesliga",
    strength: 87,
    colors: ["#fde100", "#111827"],
    continental: true,
    wageFactor: 1.08,
  },
  {
    id: "leverkusen",
    name: "Bayer 04 Leverkusen",
    league: "Bundesliga",
    strength: 89,
    colors: ["#e32221", "#111827"],
    continental: true,
    wageFactor: 1.1,
  },
  {
    id: "inter",
    name: "Inter",
    league: "Serie A",
    strength: 93,
    colors: ["#010e80", "#111827"],
    continental: true,
    wageFactor: 1.17,
  },
  {
    id: "milan",
    name: "AC Milan",
    league: "Serie A",
    strength: 87,
    colors: ["#fb090b", "#111827"],
    continental: false,
    wageFactor: 1.09,
  },
  {
    id: "juventus",
    name: "Juventus",
    league: "Serie A",
    strength: 88,
    colors: ["#f8fafc", "#111827"],
    continental: true,
    wageFactor: 1.1,
  },
  {
    id: "napoli",
    name: "Napoli",
    league: "Serie A",
    strength: 91,
    colors: ["#12a0d7", "#f8fafc"],
    continental: true,
    wageFactor: 1.13,
  },
];

export const getClub = (clubId: string) =>
  CLUBS.find((club) => club.id === clubId) ?? CLUBS[0];
